<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Article
 * @package App\Models
 * @property string $body
 */
class Article extends Model
{

    protected $fillable = [
        'title',
        'summary',
        'body',
        'cover_image',
        'category_id',
        'author_id',
        'slug',
        'views',
    ];

    protected $appends=['reading_time'];

    public function author()
    {
        return $this->belongsTo('App\User', 'author_id');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Models\Tag', 'article_tag', 'article_id', 'tag_id');
    }

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function getReadingTimeAttribute()
    {
        $word = str_word_count(strip_tags($this->body));
        $minute = floor($word / 200);
        return $minute . ' min';
   }
}
